#!/bin/bash
set -euo pipefail

# # Validate required configuration
# if [[ -z "${GITHUB_ACTOR}" || -z "${GITHUB_TOKEN}" || -z "${GITHUB_REPOSITORY}" || -z "${DOCKER_IMAGE}" || -z "${IMAGE_NAME}" ]]; then
#   echo "Missing required configuration. Please set BUILDKITE_GITHUB_ACTOR, BUILDKITE_GITHUB_TOKEN, BUILDKITE_GITHUB_REPO, and BUILDKITE_PLUGIN_PUSH_IMAGE environment variables." >&2
#   exit 1
# fi

# # Authenticate with GitHub Container Registry
# echo "${GITHUB_TOKEN}" | docker login ghcr.io -u "${GITHUB_ACTOR}" --password-stdin
# #Push the tagged Docker image to GitHub Container Registry
# docker tag "${DOCKER_IMAGE}" "ghcr.io/${GITHUB_REPOSITORY}/${DOCKER_IMAGE}:${IMAGE_NAME}"
# docker push "ghcr.io/${GITHUB_REPOSITORY}/${DOCKER_IMAGE}:${IMAGE_NAME}"
# # Push the Docker image to GitHub Container Registry
# docker tag "${DOCKER_IMAGE}" "ghcr.io/${GITHUB_REPOSITORY}/${DOCKER_IMAGE}:latest"
# docker push "ghcr.io/${GITHUB_REPOSITORY}/${DOCKER_IMAGE}:latest"

# Validate required configuration
if [[ -z "${GITHUB_ACTOR}" || -z "${GITHUB_TOKEN}" ]]; then
  echo "Missing required configuration. Please set GITHUB_ACTOR, GITHUB_TOKEN environment variables." >&2
  exit 1
fi

if [ "$login" = "true" ]; then
  echo "${GITHUB_TOKEN}" | docker login ghcr.io -u "${GITHUB_ACTOR}" --password-stdin
fi